version: '3.8'
services:
  react-demo:
    container_name: react-demo
    build:
      context: ./
    ports:
      - "5173:5173"
    # stdin_open: true
    # volumes:
    #    - ./react-docker:/usr/src/app/react-docker
    #    - /usr/src/app/react-docker/node_modules